import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { UserButton } from "@clerk/nextjs";
import logo from "../../public/gg-removebg-preview.png"
import Image from "next/image";
export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image style={{
          position: "relative",
          width: "100vw",
          height: "100vh",
          objectFit: "cover",
          backgroundPosition: "center",

        }} src="/telecommuting.jpg" alt="cover" width={2000} height={500} />
      <section style={{
        position: "absolute",
        top: "0",
        background: "linear-gradient(rgba(4, 9, 30, 0.425),rgba(4, 9, 30, 0.192))"
      }} className="header">
        <nav>
            <a href="/"> <Image src="/gg-removebg-preview.png" width={100} height={100} alt=""/> </a>
            <div className="nav-links" id="navLinks">
                <i className="fa fa-times-circle" ></i>
                <ul>
                    <li><a href="">Home</a></li>
                    <li><a href="">Services</a></li>
                    <li><a href="">About Us</a></li>
                    <li><a href="">Contact Us</a></li>
                    <li><a href="">LOG IN</a></li>

                </ul>
            </div>
            <i className="fa fa-bars"></i>
        </nav>
    <div className="text-box">
        <h1>Getting In Contact With Service Providers Was Never That Easy</h1>
        <p>Here you can choose the service that you are looking for ! <br/> Contact directly the Service Provider so that you can have a solution for the issue your stuck on it.</p>
        <a href=""className="hero-btn">Visit Us To Know More</a>
    </div>    
    </section>
    
      </div>
  </>
  
  );
}
