import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { UserButton } from "@clerk/nextjs";
import logo from "../../public/gg-removebg-preview.png"
import Image from "next/image";
import { relative } from "path";
export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
            <Head>
              <title>Task.io</title>
              <meta name="description" content="Generated by create-t3-app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
              <Image style={{
                position: "relative",
                width: "100vw",
                height: "100vh",
                objectFit: "cover",
                backgroundPosition: "center",

              }} src="/Bp1.jpg" alt="cover" width={2000} height={500} />
              <section style={{
                position: "absolute",
              top: "0",
              background: "linear-gradient(rgba(4, 9, 30, 0.425),rgba(4, 9, 30, 0.192))"
                }} className="header">
                <nav>
                <Link href="/"> <Image src="/taskio2.png" width={100} height={100} alt=""/> </Link>
                  <div className="nav-links" id="navLinks">
                      <i className="fa fa-times-circle" ></i>
                    
                          <Link href="/">Home</Link>
                          <Link href="/services">Services</Link>
                          <Link href="/">About Us</Link>
                          <Link href="/">LOG IN</Link>

                      
                  </div>
                  <i className="fa fa-bars"></i>
                  </nav>
              <div className="text-box">
              <h1>Smooth Service Provider Outreach</h1>
              <p>Here you can choose the service that you are looking for ! <br/> Contact directly the Service Provider so that you can have a solution for the issue your stuck on it.</p>
              <Link href="/"className="hero-btn">VISIT US TO KNOW MORE</Link>

              </div>    
              </section>
          
            </div>
              {/* -------About US----- */}
      <div className="about"> 
        {<Image className="about-img" src={"/r22.jpg"} alt="cover" width={2000} height={500}/> }
            <div className="about-text">
              <h1>About US</h1>
              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus, ipsum laborum temporibus facere <br />consequatur fuga a aut aperiam dicta labore laudantium cupiditate dolorum ea explicabo delectus impedit ab aliquid odit.
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus, ipsum laborum temporibus facere consequatur fuga a aut aperiam dicta labore laudantium cupiditate dolorum ea explicabo delectus impedit ab aliquid odit.</p>
              
            </div>
      </div>
      
  </>
  
  );
}
